server:
  port: 8080
#数据库连接 mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.68.253:3306/bi?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: bi2022
#spring:
#  datasource:
#    url: jdbc:sqlite::resource:rsreport.sqlite3
#    username:
#    password:
#    driver-class-name: org.sqlite.JDBC
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/*.xml
  # 实体类映射
  #type-aliases-package:
logging:
  level:
    com:
      bi:
        mapper: debug
#logging:
#  config: classpath:log4j.properties


#pagehelper:
#  helperDialect: sqlite
#  reasonable: false  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
#  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
#  pageSizeZero: true #pageSize=0 返回所有
#  params: count=countSql
